# Default values for qboxchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

frontend: 
  replicas: 1
  image:
    repository: jakob.azurecr.io/qboxcoreweb
    tag: "1.0"
    pullPolicy: IfNotPresent
  containerPort: 80    

  service:
    type: ClusterIP
    port: 80

backend:
  replicas: 1
  image:
    repository: jakob.azurecr.io/qboxcoreapi
    tag: "1.0"
    pullPolicy: IfNotPresent
  containerPort: 80

db:
  replicas: 1
  image:
    repository: microsoft/mssql-server-linux
    tag: "2017-CU9"
    pullPolicy: IfNotPresent
  containerPort: 80    
  password: "1qaz2WSX3edc"

ingress:
  name: "qbox-chart"
  prefix: "qbox-chart"
  host: "3071c04184cf486484f0.westeurope.aksapp.io"
