apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: qbox-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{.Values.ingress.hostname}}.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80