name: 2.1$(rev:.r)

trigger:
- master

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: '72c293a5-902c-4f0f-b415-743aeff8b352'
  imageRepository: 'qboxcoreweb'
  containerRegistry: 'techdays.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(build.buildnumber)'

jobs:
- job: Build
  displayName: Build
  pool:
    name: Local
  steps:

  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Azure Sponsorship'
      azureContainerRegistry: '{"loginServer":"techdays.azurecr.io", "id" : "/subscriptions/b7b2c6f7-b71e-4cd2-9e7c-409a44fe22f5/resourceGroups/techdays/providers/Microsoft.ContainerRegistry/registries/techdays"}'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Build services'  
      additionalImageTags: '$(build.buildnumber)'
      includeLatestTag: false

  - task: DockerCompose@0
    displayName: 'Push images'
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Azure Sponsorship'
      azureContainerRegistry: '{"loginServer":"techdays.azurecr.io", "id" : "/subscriptions/b7b2c6f7-b71e-4cd2-9e7c-409a44fe22f5/resourceGroups/techdays/providers/Microsoft.ContainerRegistry/registries/techdays"}'
      action: 'Push services'
      additionalImageTags: '$(build.buildnumber)'    
    
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'
  - task: HelmDeploy@0
    inputs:
      azureSubscription: 'Azure Sponsorship'
      azureResourceGroup: 'tdswe-test'
      kubernetesCluster: 'tdswe-test'
      namespace: '$(namespace)'
      command: 'package'
      chartPath: 'helm/qbox/'
      chartVersion: '$(build.buildnumber)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'