
trigger: none

variables:
  environment: qbox-dev.qbox
  ingressHostName: qbox-dev.westeurope.cloudapp.azure.com
  dbpassword: 1qaz2WSX3edc
  trafficManagerEnabled: true
  trafficManagerDNS: ndc-test.trafficmanager.net
  
resources:
  pipelines:
  - pipeline: QBox
    project: QBox
    source: QBox
    branch: master
    trigger:
          branches:
            include:
            - master    

stages:

- stage: DevTest
  displayName: Deploy stage

  jobs:
  - deployment: Deploy
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
    displayName: Deploy
    pool:
      name: Local
    environment: '$(environment)'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmInstaller@0
            inputs:
              helmVersion: '3.4.2'
              installKubectl: true
              
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'ndc-test'
              namespace: 'qbox'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Pipeline.Workspace)/QBox/drop/qbox-$(resources.pipeline.qbox.runName).tgz'
              releaseName: 'quizbox'
              overrideValues: 'frontend.image.tag=$(resources.pipeline.qbox.runName),backend.image.tag=$(resources.pipeline.qbox.runName),ingress.hostname=$(ingressHostName),db.service.port=1433,db.password=$(dbpassword),ingress.trafficManagerEnabled=$(trafficManagerEnabled),ingress.trafficManagerDNS=$(trafficManagerDNS)'
              waitForExecution: false
