trigger: none

resources:
  pipelines:
  - pipeline: QBox
    project: QBox
    source: QBox
    branch: master
    trigger:
          branches:
            include:
            - master    

stages:

- stage: Dev
  displayName: Dev
  variables:
  - group: quizbox-dev

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: Development.qbox-dev
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)
      namespace: $(namespace)

- stage: Test
  displayName: Test
  dependsOn: Dev  
  variables:
  - group: quizbox-test

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: Test.qbox-test
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)
      namespace: $(namespace)    

- stage: ProdEU
  displayName: Prod EU
  dependsOn: Test
  variables:
  - group: quizbox-prodeu

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: ProdEU.qbox
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)
      namespace: $(namespace)

- stage: ProdUS
  displayName: Prod US
  dependsOn: Test
  variables:
  - group: quizbox-produs

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: ProdUS.qbox
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)
      namespace: $(namespace)    