name: 2.1$(rev:.r)

trigger:
- master

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: '72c293a5-902c-4f0f-b415-743aeff8b352'
  imageRepository: 'qboxcoreweb'
  containerRegistry: 'jakob.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(build.buildnumber)'
  vmImageName: 'windows-2019'  

jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: $(vmImageName)
  steps:
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Azure Sponsorship'
      azureContainerRegistry: '{"loginServer":"jakob.azurecr.io", "id" : "/subscriptions/b7b2c6f7-b71e-4cd2-9e7c-409a44fe22f5/resourceGroups/acr/providers/Microsoft.ContainerRegistry/registries/jakob"}'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Build services'
      additionalImageTags: '$(build.buildnumber)'
      includeLatestTag: true

  - task: DockerCompose@0
    displayName: 'Push images'
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Azure Sponsorship'
      azureContainerRegistry: '{"loginServer":"jakob.azurecr.io", "id" : "/subscriptions/b7b2c6f7-b71e-4cd2-9e7c-409a44fe22f5/resourceGroups/acr/providers/Microsoft.ContainerRegistry/registries/jakob"}'
      action: 'Push services'
      additionalImageTags: '$(build.buildnumber)'        
    
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: '3.4.2'
      
  - task: HelmDeploy@0
    inputs:
      command: 'package'
      chartPath: 'helm/qbox'
      chartVersion: '$(build.buildnumber)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'