trigger: none

resources:
  pipelines:
  - pipeline: QBox
    project: QBox
    source: QBox
    branch: master
    trigger:
          branches:
            include:
            - master    

stages:

- stage: DevTest
  displayName: Deploy stage
  variables:
  - group: quizbox-dev

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: $(environment)
      kubernetesServiceConnection: ndc-test
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)

- stage: ProdEU
  displayName: Deploy stage
  variables:
  - group: quizbox-prodeu

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: $(environment)
      kubernetesServiceConnection: ndc-test
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)

- stage: ProdUS
  displayName: Deploy stage
  variables:
  - group: quizbox-produs

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: $(environment)
      kubernetesServiceConnection: ndc-test
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)      