name: 2.1$(rev:.r)

trigger:
- master

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: '72c293a5-902c-4f0f-b415-743aeff8b352'
  imageRepository: 'qboxcoreweb'
  containerRegistry: 'techdays.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(build.buildnumber)'

stages:
- stage: Build
  displayName: Build

  jobs:  
  - template: build-qbox.yml

- stage: DeployDev
  displayName: Deploy Dev
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Local
    environment: 'devtest.qbox-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self          
          - template: deploy-qbox.yml
            parameters:
              namespace: 'qbox-dev'
              kubernetesServiceConnection: 'qbox-dev'  
              ingressHostName: 'techdays.westeurope'

- stage: DeployStaging
  displayName: Deploy Staging
  dependsOn: DeployDev
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Local
    environment: 'devtest.qbox-staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self          
          - template: deploy-qbox.yml
            parameters:
              namespace: 'qbox-staging'
              kubernetesServiceConnection: 'qbox-staging'  
              ingressHostName: 'techdays.westeurope'

- stage: DeployProdEU
  displayName: Deploy ProdEU
  dependsOn: DeployStaging
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Local
    environment: 'prodeu.qbox'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self          
          - template: deploy-qbox.yml
            parameters:
              namespace: 'qbox'
              kubernetesServiceConnection: 'qbox-prodeu'  
              ingressHostName: 'techdays.westeurope'              

- stage: DeployProdUS2
  displayName: Deploy ProdUS2
  dependsOn: DeployStaging
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Local
    environment: 'produs2.qbox'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self          
          - template: deploy-qbox.yml
            parameters:
              namespace: 'qbox'
              kubernetesServiceConnection: 'qbox-produs2'  
              ingressHostName: 'techdays.westeurope'                            