
trigger: none

 
resources:
  pipelines:
  - pipeline: QBox
    project: QBox
    source: QBox
    branch: master
    trigger:
          branches:
            include:
            - master    

stages:

- stage: DevTest
  displayName: Deploy stage
  variables:
  - group: quizbox-dev

  jobs:
  - template: deploy-template.yml  # Template reference
    parameters:
      environment: $(environment)
      kubernetesServiceConnection: ndc-test
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)