name: 2.1$(rev:.r)

trigger:
- master

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: '72c293a5-902c-4f0f-b415-743aeff8b352'
  imageRepository: 'qboxcoreweb'
  containerRegistry: 'techdays.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(build.buildnumber)'

jobs:
- job: Build
  displayName: Build
  pool:
    name: Local
  steps:

  - task: Docker@2
    inputs:
      containerRegistry: 'techdays'
      repository: 'qboxcorapi'
      command: 'buildAndPush'
      Dockerfile: 'Source/QBoxCore.API/Dockerfile'
      buildContext: 'Source/'
      tags: '$(Build.BuildNumber)'

  - task: Docker@2
    inputs:
      containerRegistry: 'techdays'
      repository: 'qboxcoreweb'
      command: 'buildAndPush'
      Dockerfile: 'Source/QBoxCore.Web/Dockerfile'
      buildContext: 'Source/'
      tags: '$(Build.BuildNumber)'      
    
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'

  - task: HelmDeploy@0
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: 'Azure Sponsorship'
      azureResourceGroup: 'tdswe-test'
      kubernetesCluster: 'tdswe-test'
      command: 'init'
      upgradeTiller: false
      arguments: '--client-only'
      
  - task: HelmDeploy@0
    inputs:
      command: 'package'
      chartPath: 'helm/qbox'
      chartVersion: '$(build.buildnumber)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'