trigger: none

resources:
  pipelines:
  - pipeline: QBox
    project: QBox
    source: QBox
    branch: master
    trigger:
          branches:
            include:
            - master    

stages:

- stage: Dev
  displayName: Dev
  variables:
  - group: quizbox-dev

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: ndc-test
      kubernetesServiceConnection: ndc-dev
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)

- stage: Test
  displayName: Test
  dependsOn: Dev  
  variables:
  - group: quizbox-test

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: ndc-test
      kubernetesServiceConnection: ndc-test
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)      

- stage: ProdEU
  displayName: Prod EU
  dependsOn: Test
  variables:
  - group: quizbox-prodeu

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: ndc-prodeu
      kubernetesServiceConnection: ndc-prodeu
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)

- stage: ProdUS
  displayName: Prod US
  dependsOn: Test
  variables:
  - group: quizbox-produs

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: ndc-produs
      kubernetesServiceConnection: ndc-produs
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)      