#Deployment pipeline for QBox, deploys latest version of QBox pipeline
trigger: none

resources:
  pipelines:
  - pipeline: QBox
    project: QBox
    source: QBox
    branch: master
    trigger:
      branches:
        include:
        - master    

stages:

- stage: DevTest
  displayName: DevTest  
  variables:
  - group: quizbox-dev

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: DevTest.qbox
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)
      namespace: $(namespace)

- stage: ProdEU
  displayName: Prod EU
  dependsOn: Dev
  variables:
  - group: quizbox-prodeu

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: ProdEU.qbox
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)
      namespace: $(namespace)

- stage: ProdUS
  displayName: Prod US
  dependsOn: Dev
  variables:
  - group: quizbox-produs

  jobs:
  - template: deploy-template.yml
    parameters:
      environment: ProdUS.qbox
      ingressHostName: $(ingressHostName)
      dbpassword: $(dbpassword)
      trafficManagerEnabled: $(trafficManagerEnabled)
      trafficManagerDNS: $(trafficManagerDNS)
      namespace: $(namespace)    