name: 2.1$(rev:.r)

trigger:
- master

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: '72c293a5-902c-4f0f-b415-743aeff8b352'
  imageRepository: 'qboxcoreweb'
  containerRegistry: 'techdays.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(build.buildnumber)'

stages:
- stage: Build
  displayName: Build stage

  jobs:  
  - template: build-qbox.yml

- stage: DeployTest
  displayName: Deploy Test
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Local
    environment: 'qbox-test.qbox-test.techdays-eu'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self          
          - template: deploy-qbox.yml
            parameters:
              namespace: 'qbox-test'
              kubernetesServiceConnection: 'qbox-test-techdays-eu'     

- stage: DeployTestUS
  displayName: Deploy Test
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Local
    environment: 'qbox-test.qbox-test.techdays-us'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self          
          - template: deploy-qbox.yml
            parameters:
              namespace: 'qbox-test'
              kubernetesServiceConnection: 'qbox-test-techdays-us'     
