name: 2.1$(rev:.r)

trigger:
- master

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: '72c293a5-902c-4f0f-b415-743aeff8b352'
  imageRepository: 'qboxcoreweb'
  containerRegistry: 'techdays.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(build.buildnumber)'

stages:
- stage: Build
  displayName: Build

  jobs:  
  - template: build-qbox.yml

- stage: DeployDev
  displayName: Deploy Dev
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Local
    environment: 'devtest.qbox-test'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self          
          - template: deploy-qbox.yml
            parameters:
              namespace: 'qbox-test'
              kubernetesServiceConnection: 'qbox-dev'  
              ingressHostName: 'techdays.westeurope'
