# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '190e78dc-156b-42bd-be70-7b6d888f1a5c'
  imageRepository: 'qboxcoreweb'
  containerRegistry: 'jakob.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'jakob4558098b-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
  # Name of the new namespace being created to deploy the PR changes.
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

resources:
  pipelines:
  - pipeline: QBox
    project: QBox
    source: QBox
    branch: master

stages:

- stage: DevTest
  displayName: Deploy stage

  jobs:
  - deployment: Deploy
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'QBox.qbox'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Azure Sponsorship'
              azureResourceGroup: 'ndc-test'
              kubernetesCluster: 'ndc-test'
              namespace: 'qbox'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(System.DefaultWorkingDirectory)/_QBox/drop/qbox-$(build.buildnumber).tgz'
              releaseName: 'traefik'
              overrideValues: 'frontend.image.tag=$(build.buildnumber),backend.image.tag=$(build.buildnumber),ingress.hostname=ndc-test-2f685e2a.hcp.westeurope.azmk8s.io,db.service.port=1433'
              waitForExecution: false
