parameters:
- name: environment
  type: string
- name: kubernetesServiceConnection
  type: string  
- name: ingressHostName
  type: string
- name: dbpassword
  type: string
- name: trafficManagerEnabled
  type: string
- name: trafficManagerDNS
  type: string      
  
jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Local
    environment: '${{ parameters.environment }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmInstaller@0
            inputs:
              helmVersion: '3.4.2'
              installKubectl: true
              
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: '${{ parameters.kubernetesServiceConnection }}'
              namespace: 'qbox'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Pipeline.Workspace)/QBox/drop/qbox-$(resources.pipeline.qbox.runName).tgz'
              releaseName: 'quizbox'
              overrideValues: 'frontend.image.tag=$(resources.pipeline.qbox.runName),backend.image.tag=$(resources.pipeline.qbox.runName),ingress.hostname=${{ parameters.ingressHostName }},db.service.port=1433,db.password=${{ parameters.dbpassword }},ingress.trafficManagerEnabled=${{ parameters.trafficManagerEnabled }},ingress.trafficManagerDNS=${{ parameters.trafficManagerDNS }}'
              waitForExecution: false