version: '3'

services:
  dev:
    image: mcr.microsoft.com/devcontainers/dotnet:0-3.1
    volumes:
      - .:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    
  db:
     image: "mcr.microsoft.com/mssql/server:2019-latest"
     ports:
     - "1433:1433"
     environment:
       SA_PASSWORD: "1qaz2WSX3edc"
       ACCEPT_EULA: "Y"
       MSSQL_PID: "Express"
