apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  template:
    metadata:
      labels:
        app: qbox
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: {{ .Values.db.replicas }}
  template:
    metadata:
      labels:
        tier: db
    spec:
      containers:
      - name: db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        ports:
        - containerPort: {{ .Values.db.containerPort }}
        env:
        - name: SA_PASSWORD
          value: "{{ .Values.db.password }}"
        - name: ACCEPT_EULA
          value: "Y"        
