apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    metadata:
      labels:
        app: qbox
        tier: backend
    spec:
      containers:
      - name: backend
        image: jakobehn/qboxcoreapi:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: qbox
spec:
  selector:
    app: qbox
    tier: backend
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP

