apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: qbox
spec:
  selector:
    app: qbox
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30081
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
#  minReadySeconds: 10
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: qbox
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: jakob.azurecr.io/qboxcoreweb:2.0
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regsecret   