apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: qbox
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: qbox.3071c04184cf486484f0.westeurope.aksapp.io
    http:
      paths:
      - path: /  
        backend:
          serviceName: frontend
          servicePort: 80
  - host: qboxapi.3071c04184cf486484f0.westeurope.aksapp.io
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 80
                     