apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: winops.azurecr.io/qboxcoreweb:1.0 
        volumeMounts:
        - mountPath: "/var/lib/storage"
          name: volume          
        ports:
        - containerPort: 80
        imagePullPolicy: Always      
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile          