# Default values for qboxchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
frontend: 
  image:
    repository: techdays.azurecr.io/qboxcoreweb
    tag: "1.1"
    pullPolicy: IfNotPresent
  containerPort: 80    

  service:
    type: ClusterIP
    port: 80

backend:
  image:
    repository: techdays.azurecr.io/qboxcoreapi
    tag: "1.1"
    pullPolicy: IfNotPresent
  containerPort: 80

db:
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: "2017-latest-ubuntu"
    pullPolicy: IfNotPresent
  containerPort: 80    
  password: 1qaz2WSX3edc

ingress:
  hostname: techdays.somewhere.com
  publichostname: 

