version: '3'

services:
  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "81:80"
networks:
  default:
    external:
      name: nat
