version: '3'

services:
  web:
    image: qboxcoreweb
    build:
      context: .
      dockerfile: QBoxCore.Web/Dockerfile

  api:
    image: qboxcoreapi
    build:
      context: .
      dockerfile: QBoxCore.Api/Dockerfile

  db:
     image: "microsoft/mssql-server-linux"
     environment:
       SA_PASSWORD: "1qaz2WSX3edc"
       ACCEPT_EULA: "Y"

