version: '3.4'

services:
  web:
    image: qboxcoreweb
    build:
      context: .
      dockerfile: QBoxCore.Web/Dockerfile
    volumes:
       - c:/storage:/var/lib/storage
  api:
    image: qboxcoreapi
    build:
      context: .
      dockerfile: QBoxCore.Api/Dockerfile


  db:
     image: "microsoft/mssql-server-linux"
     ports:
     - "1433:1433"
     environment:
       SA_PASSWORD: "1qaz2WSX3edc"
       ACCEPT_EULA: "Y"
       MSSQL_PID: "Express"
